#!/usr/bin/python3
import matplotlib.pyplot as plt
import sys
import math
import pandas as pd
from tuning import helper
from tuning import temperament
from tuning import edo12

if __name__ == "__main__":

    fig = plt.figure()

    freqlist = []

    for n, f in enumerate(sys.argv[1:]):

        df = pd.read_csv(f)

        # Plot theoretical frequency
        length = df['Length']
        lmin = min(length)
        lmax = max(length)
        D = df['D'][0]
        d = df['d'][0]
        g = df['g'][0]

        # The speed of sound through air is approximately 343 m/s at normal room temperature, which is at 20 °C
        sound_speed = 343

        # On the Radiation of Sound from an Unflanged Circular Pipe
        # by HAROLD LEVINE AND JULIAN. SCHVHNGER gives 0.6133 as end correction
        end_correction = 0.6133 * d / 2

        front_correction = 50 # mm, experimental, needs explanation

        lrange = range(lmin, lmax, 1)
        frequency = [sound_speed / ((front_correction + l + end_correction) / 1000) for l in lrange]
        plt.plot(lrange, frequency, label="Theoretical H2 frequency for d={}mm (Hz)".format(d))

        h1 = df['H2']
        frequency = [x for x in h1]
        freqlist += frequency
        plt.plot(length, frequency, marker='o', label=f)

    # Plot the 12-TET note names
    freq_min = min(freqlist)
    freq_max = max(freqlist)
    t = edo12.EDO12()
    t = t.filtered(lambda elem : elem[1] >= freq_min and elem[1] <= freq_max)
    note_name = list(t.keys())
    note_value = list(t.values())
    maxlength = max(length)
    for i, value in enumerate(note_value):
        plt.axhline(y=value, linestyle=':')
        plt.text(maxlength, value, note_name[i])

    # Plot some other flutes for comparison
    plt.plot([770], [387], marker='o', label="Mansur H2 (Hz)")
    plt.plot([770], [421], marker='o', label="PPR #1 H2 (Hz)")
    plt.plot([770], [409], marker='o', label="Kaval H2 (Hz)")

    plt.xlabel("Tube length (mm)")
    plt.ylabel("Frequency (Hz)")
    plt.legend()

    plt.show()

