#!/usr/bin/python3
import matplotlib.pyplot as plt
import sys
import math
import pandas as pd

if __name__ == "__main__":

    fig = plt.figure()

    for n, f in enumerate(sys.argv[1:]):

        df = pd.read_csv(f)

        # Plot theoretical frequency
        length = df['Length']
        lmin = min(length)
        lmax = max(length)
        D = df['D'][0]
        d = df['d'][0]
        g = df['g'][0]
        sound_speed = 343
        end_correction = 0.6 * d
        front_correction = 33 # mm, experimental, needs explanation
        lrange = range(lmin, lmax, 1)
        frequency = [sound_speed / ((front_correction + l + end_correction) / 1000) for l in lrange]
        plt.plot(lrange, frequency, label="Theoretical frequency for d={}mm (Hz)".format(d))

        h1 = df['H1']
        frequency = [x for x in h1]
        plt.plot(length, frequency, marker='o', label=f)

    # Plot the 12-TET note names
    note_name = df['Note']
    note_value = df['12-TET H1']
    maxlength = max(length)
    for i, value in enumerate(note_value):
        plt.axhline(y=value, linestyle=':')
        plt.text(maxlength, value, note_name[i])


    # Plot some other flutes for comparison
    plt.plot([770], [387], marker='o', label="Mansur H1 (Hz)")
    plt.plot([770], [421], marker='o', label="PPR #1 H1 (Hz)")
    plt.plot([770], [409], marker='o', label="Kaval H1 (Hz)")

    plt.xlabel("Tube length (mm)")
    plt.ylabel("Frequency (Hz)")
    plt.legend()

    plt.show()

